name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: get-cache-path
        run: echo "::set-output name=path::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
      - run: npm install
      - run: npm run build
      - run: ls dist
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist
          commit_message: npm run build
